# Generated by Django 3.1.2 on 2020-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='classes',
            field=models.CharField(choices=[('1', 'Sat AM'), ('2', 'Sat PM'), ('3', 'Sun AM'), ('4', 'Sun PM')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='students',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('G', 'GCSE'), ('AS', 'AS-Level'), ('A', 'A-Level')], default=1, max_length=2),
        ),
    ]
