# Generated by Django 3.1.2 on 2020-10-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
                ('image_path', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('classes', models.CharField(choices=[('1', 'Sat AM'), ('2', 'Sat PM'), ('3', 'Sun AM'), ('4', 'Sun PM')], default=1, max_length=2)),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('G', 'GCSE'), ('AS', 'AS-Level'), ('A', 'A-Level')], default=1, max_length=2)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
