# Generated by Django 3.1.2 on 2020-10-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
