# Generated by Django 3.1.2 on 2020-10-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201013_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'answer_1'), ('2', 'answer_2'), ('3', 'answer_3'), ('4', 'answer_4')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='quiz',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='classes',
            field=models.CharField(choices=[('1', 'Sat AM'), ('2', 'Sat PM'), ('3', 'Sun AM'), ('4', 'Sun PM'), ('5', 'All')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'GCSE'), ('8', 'AS-Level'), ('9', 'A-Level'), ('10', 'All')], default=1, max_length=2),
        ),
    ]
