# Generated by Django 3.1.2 on 2020-10-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='descripiton',
            new_name='description',
        ),
    ]
