# Generated by Django 3.1.2 on 2020-10-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('homework', '0002_auto_20201012_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.OneToOneField(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
            preserve_default=False,
        ),
    ]
