# Generated by Django 3.1.2 on 2020-10-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20201012_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='classes',
            field=models.CharField(choices=[('1', 'Sat AM'), ('2', 'Sat PM'), ('3', 'Sun AM'), ('4', 'Sun PM')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='homework',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('G', 'GCSE'), ('AS', 'AS-Level'), ('A', 'A-Level')], default=1, max_length=2),
        ),
    ]
