# Generated by Django 3.1.2 on 2020-10-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20201012_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'GCSE'), ('8', 'AS-Level'), ('9', 'A-Level')], default=1, max_length=2),
        ),
    ]
